//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DinhMuc
    {
        public int TuoiCuaCay { get; set; }
        public int LoaiCay { get; set; }
        public Nullable<int> TienChamSoc { get; set; }
    
        public virtual LoaiCay LoaiCay1 { get; set; }
    }
}
